[package]
name = "rust-lists-exercise"
version = "0.1.0"
authors = ["MathxH Chen <brainfvck@foxmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
